#!/usr/bin/env python3
"""Measure matte quality, and compare runs.

Thin CLI over cleanplate.metrics - the app renders the same table.

    python src/metrics.py \
        --run "walk v1 (binary)=outputs/walk/masks" \
        --run "walk v2 (refined)=outputs/walk_v2/alpha" \
        --table docs/METRICS.md

Shape metrics binarise at alpha > 127 so a soft matte and a binary one are compared
on the same footing. Fragmentation is reported as *significant* components (>=1% of
the largest); the raw count is dominated by 1-2 pixel specks over the threshold.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import _bootstrap  # noqa: F401
from cleanplate import metrics, runs
from cleanplate.paths import ROOT, rel

PREAMBLE = ("Generated by `src/metrics.py`. Shape metrics binarise at alpha > 127 so a "
            "soft\nmatte and a binary one are compared on the same footing.\n\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run", action="append", required=True, metavar="LABEL=PATH")
    ap.add_argument("--table", type=Path)
    ap.add_argument("--title", default="Matte quality")
    ap.add_argument("--append", action="store_true")
    ap.add_argument("--no-json", action="store_true")
    args = ap.parse_args()

    measured = []
    for spec in args.run:
        if "=" not in spec:
            sys.exit(f"--run needs LABEL=PATH, got {spec!r}")
        label, path = spec.split("=", 1)
        d = Path(path)
        if not d.is_absolute() and not d.exists():
            d = ROOT / d
        try:
            m = metrics.measure(runs.load_seq(d), label.strip())
        except FileNotFoundError as e:
            sys.exit(str(e))
        m["source"] = rel(d)
        measured.append(m)
        print(f"[metrics] {m['label']}: {m['frames']} frames  "
              f"flicker mean {m['area_change_pct']['mean']:.2f}%  "
              f"IoU min {m['iou_consecutive']['min']:.3f}  "
              f"soft {100 * m['softness']['soft_pixel_fraction_mean']:.3f}%  "
              f"sig-components mean {m['components']['significant_mean']:.2f}")
        if not args.no_json:
            out = runs.save_json(m, d.parent / "metrics.json")
            print(f"[metrics]   -> {rel(out)}")

    md = metrics.table(measured)
    print("\n" + md)
    if args.table:
        args.table.parent.mkdir(parents=True, exist_ok=True)
        if args.append and args.table.exists():
            with args.table.open("a") as fh:
                fh.write(f"\n## {args.title}\n\n" + md + "\n")
        else:
            args.table.write_text(f"# {args.title}\n\n" + PREAMBLE + md + "\n")
        print(f"\n[metrics] table -> {args.table}")


if __name__ == "__main__":
    main()
